[package]
name = "wave-function-collapse"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
bitvec = "1.0"

[[example]]
name = "sudoku"
crate-type = ["bin"]